import { Transaction } from "@/types/transaction";

export const transactionsData: Transaction[] = [
  {
    id: "split-camp-123",
    type: "payment",
    description: "キャンプ用品費用（立替）",
    date: "2025/04/10",
    amount: -18600,
    ecoContribution: {
      enabled: true,
      amount: 186,
    },
    badges: ["割り勘", "完了"],
  },
  {
    id: "split-fuji-456",
    type: "payment",
    description: "富士山登山費用（立替）",
    date: "2025/03/15",
    amount: -24000,
    ecoContribution: {
      enabled: true,
      amount: 240,
    },
    badges: ["割り勘", "進行中"],
  },
  {
    id: "txn_1",
    type: "payment",
    description: "エコ製品定期プラン",
    date: "2025/04/19",
    amount: -4000,
    ecoContribution: {
      enabled: true,
      amount: 200,
    },
  },
  {
    id: "txn_2",
    type: "charge",
    description: "Eco Walletチャージ",
    date: "2025/04/15",
    amount: 10000,
  },
  {
    id: "txn_3",
    type: "payment",
    description: "オーガニックコットンTシャツ",
    date: "2025/04/10",
    amount: -3200,
    ecoContribution: {
      enabled: true,
      amount: 150,
    },
    badges: ["環境貢献"],
  },
  {
    id: "txn_4",
    type: "payment",
    description: "リサイクルフリース",
    date: "2025/04/05",
    amount: -12000,
    ecoContribution: {
      enabled: true,
      amount: 500,
    },
    badges: ["環境貢献"],
  },
  {
    id: "txn_5",
    type: "receive",
    description: "友達紹介ボーナス",
    date: "2025/04/03",
    amount: 1000,
    badges: ["特典"],
  },
  {
    id: "txn_6",
    type: "expired",
    description: "エコポイント期限切れ",
    date: "2025/04/02",
    amount: -500,
    badges: ["期限切れ"],
  },
  {
    id: "txn_7",
    type: "charge",
    description: "Eco Walletチャージ",
    date: "2025/04/01",
    amount: 20000,
  },
  // 追加のテストデータ（もっと見るボタンの動作確認用）
  {
    id: "txn_8",
    type: "payment",
    description: "バンブー製水筒",
    date: "2025/03/28",
    amount: -2800,
    ecoContribution: {
      enabled: true,
      amount: 140,
    },
    badges: ["環境貢献"],
  },
  {
    id: "txn_9",
    type: "payment",
    description: "オーガニック野菜セット定期購入",
    date: "2025/03/25",
    amount: -3500,
    ecoContribution: {
      enabled: true,
      amount: 175,
    },
  },
  {
    id: "txn_10",
    type: "receive",
    description: "キャンペーン特典",
    date: "2025/03/20",
    amount: 1500,
    badges: ["特典"],
  },
  {
    id: "txn_11",
    type: "charge",
    description: "Eco Walletチャージ",
    date: "2025/03/18",
    amount: 15000,
  },
  {
    id: "txn_12",
    type: "payment",
    description: "リサイクルペーパーノート",
    date: "2025/03/12",
    amount: -980,
    ecoContribution: {
      enabled: true,
      amount: 50,
    },
    badges: ["環境貢献"],
  },
  {
    id: "txn_13",
    type: "payment",
    description: "環境保全イベント参加費",
    date: "2025/03/05",
    amount: -1500,
    ecoContribution: {
      enabled: true,
      amount: 300,
    },
    badges: ["環境貢献", "イベント"],
  },
  {
    id: "txn_14",
    type: "expired",
    description: "キャンペーンポイント期限切れ",
    date: "2025/03/01",
    amount: -750,
    badges: ["期限切れ"],
  },
  {
    id: "txn_15",
    type: "charge",
    description: "Eco Walletチャージ",
    date: "2025/02/28",
    amount: 5000,
  },
  {
    id: "txn_16",
    type: "payment",
    description: "再生素材バッグ",
    date: "2025/02/25",
    amount: -4500,
    ecoContribution: {
      enabled: true,
      amount: 225,
    },
    badges: ["環境貢献"],
  },
  {
    id: "txn_17",
    type: "receive",
    description: "紹介特典ボーナス",
    date: "2025/02/20",
    amount: 2000,
    badges: ["特典"],
  },
  {
    id: "txn_18",
    type: "payment",
    description: "エコフレンドリー洗剤セット",
    date: "2025/02/15",
    amount: -2100,
    ecoContribution: {
      enabled: true,
      amount: 105,
    },
  },
  {
    id: "txn_19",
    type: "charge",
    description: "Eco Walletチャージ",
    date: "2025/02/10",
    amount: 10000,
  },
  {
    id: "txn_20",
    type: "payment",
    description: "サステナブルファッションアイテム",
    date: "2025/02/05",
    amount: -7800,
    ecoContribution: {
      enabled: true,
      amount: 390,
    },
    badges: ["環境貢献"],
  },
];
